---

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  notify: Reboot host
  tags: hostname

- name: Ensure local hostname entry exists in /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    state: present
    regexp: '^127\.0\.1\.1\s+'
    line: "127.0.1.1 {{ inventory_hostname }} {{ inventory_hostname_short }}"
    insertafter: '^127\.0\.0\.1'
  tags: hostname
