---

# The networking backend.
# Options: 'networkd', 'NetworkManager'.
netplan_renderer: networkd

# The ethernet device interfaces.
netplan_ethernets:
    # The interface name.
  - interface: '{{ ansible_default_ipv4.interface }}'

    # Enable DHCP for IPv4.
    dhcp4: true

    # Enable DHCP for IPv6.
    dhcp6: false

    # Accept Router Advertisement that would have the kernel configure IPv6 by itself.
#   accept_ra: true

    # A list of static addresses in addition to ones received through DHCP or RA.
#   addresses:

    # A collection of DNS servers and search domains.
#   nameservers:
      # A list of IPv4 or IPv6 addresses.
#     addresses:

      # A list of search domains.
#     search:

    # A list of static routing for the device.
#   routes:
        # The destination address for the route.
#     - to: default

        # The address to the gateway to use for this route.
#       via: <gateway>

        # Specifies if the route is directly connected to the interface.
#       on_link: true

    # systemd.networkd overrides.
#   networkd_overrides:
      # The configuration for the IPv6 Router Advertisement (RA) client.
#     ipv6_accept_ra:
        # The DNS servers received in the Router Advertisement will be used.
#       use_dns: true
