---

- name: Install UFW
  ansible.builtin.apt:
    name: ufw
    state: "{{ 'latest' if apt_update_latest else 'present' }}"
    update_cache: '{{ apt_update_cache }}'
    cache_valid_time: '{{ apt_cache_valid_time }}'
  tags:
    - firewall
    - update

- name: Disable and reset firewall to defaults
  community.general.ufw:
    state: reset
  when: firewall_reset
  tags: firewall

- name: Set default policy for outgoing traffic
  community.general.ufw:
    default: '{{ firewall_outgoing }}'
    direction: outgoing
  tags: firewall

- name: Set default policy for incoming traffic
  community.general.ufw:
    default: '{{ firewall_incoming }}'
    direction: incoming
  tags: firewall

- name: Set logging
  community.general.ufw:
    logging: '{{ firewall_logging }}'

- name: Allow access to SSH
  community.general.ufw:
    rule: allow
    port: '{{ ssh_port }}'
    proto: tcp
    comment: Allow SSH
  tags: firewall

- name: Apply access rule
  community.general.ufw:
    rule: '{{ item.rule }}'
    port: '{{ item.port }}'
    proto: '{{ item.protocol }}'
    comment: "{{ item.comment | default('') }}"
  loop: '{{ firewall_rules | default([], true) }}'
  tags: firewall

- name: Reload and enable firewall on boot
  community.general.ufw:
    state: enabled
  tags: firewall
